### PR TITLE
Adding Contact.contact_persons.

### PR DESCRIPTION
**Pull request by dslh**
This PR exposes the [`ContactPerson`](https://developer.xero.com/documentation/api/contacts/#contact-persons) entity that may be supplied as a part of a `Contact` structure. I wasn't really sure what to test! But it's a small enough feature.

@gohiring/engineers, please review this open source contribution :wink:

### CODE REVIEW

**Comment by dnesteryuk** [comment]
@dslh Maybe we can write kind of an integration test to make sure the contact person entity get included into a request. The request can be stubbed by `VCR`. What do you think? :eyes: I guess some integration tests are [here](https://github.com/gohiring/xero/blob/master/spec/lib/xero/clients/private_application_spec.rb).

**Comment by dslh** [comment]
Hi @dnesteryuk! Finally, I worked out how to access Xero's demo company to get some fresh test data. I had to fix up a couple of missing fields for the `Item` model and edit the tests a bit to get them working with the new data, but finally we're testing that the `ContactPerson` model is serialized successfully. Please re-review :smile:

**Comment by dnesteryuk** [comment]
@dslh Woohooo, it looks great! :+1: Just one small note :blush: Can we get rid of [authorization info](https://github.com/dslh/xero/blob/aeb47b66ce61c2d53fe3d087b7b44ccb0fddf0d1/spec/vcr_cassettes/invoices.yml#L17) in cassettes? It can be achieved with this [option](https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/filter-sensitive-data).

**Comment by dslh** [comment]
Ok, our OAuth key is removed from the test fixtures. I will delete the application from my Xero account as well.

I have left the existing credentials in [`spec/support/helpers.rb`](https://github.com/gohiring/xero/pull/5/files#diff-3bb5ea059ab3c1c6dbccd241014d50b2R3) but I added some instructions for re-generating test data. The credentials in the file have expired since a long time ago.

Please re-review. Thanks @dnesteryuk!

**Comment by dnesteryuk** [comment]
Well done, Doug! :clap:  Please, ship! :wink:

**Pull request merged**
