### PR TITLE
Fix and improve tests

### PR DESCRIPTION
**Pull request by SweeD**
I improved the tests to run with the newest rspec version, use expect syntax, etc

@soulim please review :smile:

### CODE REVIEW

**Comment by SweeD** [comment]
Could you please add *this* repository to Travis or CircleCi, so we can use the right badge here, as well? :wink:

**Comment by soulim** [comment]
Ta-da! :tada: 

```markdown
[![Circle CI](https://circleci.com/gh/gohiring/xero.svg?style=svg&circle-token=ec8f29a58a76aed94881f13e756888ec9aafc762)](https://circleci.com/gh/gohiring/xero)
```

**Comment by SweeD** [comment]
Ok, everything is working and set up. 

It's ready to merge, if you finished review and give a  :+1: 
@soulim   :wink:

**Comment by dslh** [comment]
Changes look good to me! All my tests are passing now :clap: :smile: 

While you're tidying up can I maybe ask for one thing added to the commit? I see that [`rspec-spies`](https://github.com/technicalpickles/rspec-spies) is obsolete and can be removed from the `Gemfile`. With it, I can't generate a `Gemfile.lock`.

**Comment by SweeD** [comment]
@dslh Done. :smile:

**Comment by dslh** [comment]
Thanks! :cake:

**Pull request merged**
