### PR TITLE
Feature/add api url config

### PR DESCRIPTION
**Pull request by SweeD**
Implement a config for the endpoint url.

@gohiring/api-dev  Please review :smile:

### CODE REVIEW

**Comment by SweeD** [comment]
It totally is! :wink: 

But the config has changed from `api_url` to `api_host` :smile:

**Comment by dslh** [comment]
Looks great, I like what you've done with `configuration.rb` :smile:

Not sure about that one `require` but otherwise it's :+1: from me!

**Comment by soulim** [comment]
I have the same question :smile: Where required `ActiveSupport::Deprecation` is used?..

**Comment by SweeD** [comment]
screen shot 2015-12-15 at 17 04 11

**Comment by soulim** [comment]
Thank you for explanation @SweeD :smile: :+1: 

It's simple curiosity. Would it make sense to require `ActiveSupport::Deprecation` in `spec/spec_helper.rb` then?.. I mean if just `shoulda-matchers` requires this library, then might be enough to load it when tests are running.

**Comment by SweeD** [comment]
`shoulda-matchers` where the only ones who tried to print deprecation messages with it, so there has been the errors. 

We could move it, yeah. 

I'll do that with in a simple commit in master, if that's okay? 
This one is already in master

**Comment by soulim** [comment]
Simple follow-up pull request should be also fine :wink:

**Pull request merged**
